### ISSUE TITLE
Much English, such wow!

### ISSUE THREAD

**Issue by jalako** [Samake/MTA-RPG#5]
"This is a simple diablo style gamemode for multitheftauto.com! Is still in development and not playable yet!"

müsste zu
"This is a simple Diablo style gamemode for multitheftauto.com! It is still in development and not playable yet!

"An multitheft auto diablo style gamemode"

müsste zu

"A multitheft auto diablo style gamemode"

werden

**Comment by Samake** [comment]
Thanks xD

**Comment by Samake** [comment]
Changed description. Thanks jalako.
